### ISSUE TITLE
Wraith FocusAI throws npe

### ISSUE THREAD

**Issue by cyberpwnn** [PhantomAPI/Phantom#42]
``` java
java.lang.NullPointerException
        at org.phantomapi.wraith.FocusAIController.onTick(FocusAIController.java:40) ~[?:?]
        at org.phantomapi.wraith.PhantomWraith.tick(PhantomWraith.java:64) ~[?:?]
        at org.phantomapi.core.WraithController.onTick(WraithController.java:32) ~[?:?]
        at org.phantomapi.construct.Controller.tick(Controller.java:147) ~[?:?]
        at org.phantomapi.construct.ControllablePlugin$6$2$1.run(ControllablePlugin.java:359) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
```

**Comment by cyberpwnn** [comment]
Still an issue

**Comment by cyberpwnn** [comment]
``` java
java.lang.NullPointerException
        at org.phantomapi.wraith.WraithTarget.getTarget(WraithTarget.java:76) ~[?:?]
        at org.phantomapi.wraith.FocusAIController.onTick(FocusAIController.java:40) ~[?:?]
        at org.phantomapi.wraith.PhantomWraith.tick(PhantomWraith.java:64) ~[?:?]
        at org.phantomapi.core.WraithController.onTick(WraithController.java:32) ~[?:?]
        at org.phantomapi.construct.Controller.tick(Controller.java:147) ~[?:?]
        at org.phantomapi.construct.ControllablePlugin$6$2$1.run(ControllablePlugin.java:359) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
```
