### ISSUE TITLE
Nest Api Unload Exceptions

### ISSUE THREAD

**Issue by cyberpwnn** [PhantomAPI/Phantom#69]
### Unload Exception (Blocks Map is Null)

```
[13:07:57] [Server thread/ERROR]: Could not pass event ChunkUnloadEvent to Phantom vP2
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[paperspigot-1.8.8.jar:git-PaperSpigot-8b18730]
    at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[paperspigot-1.8.8.jar:git-PaperSpigot-8b18730]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[paperspigot-1.8.8.jar:git-PaperSpigot-8b18730]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [paperspigot-1.8.8.jar:git-PaperSpigot-8b18730]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [paperspigot-1.8.8.jar:git-PaperSpigot-8b18730]
    at net.minecraft.server.v1_8_R3.ChunkProviderServer.unloadChunks(ChunkProviderServer.java:369) [paperspigot-1.8.8.jar:git-PaperSpigot-8b18730]
    at net.minecraft.server.v1_8_R3.WorldServer.doTick(WorldServer.java:234) [paperspigot-1.8.8.jar:git-PaperSpigot-8b18730]
    at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:830) [paperspigot-1.8.8.jar:git-PaperSpigot-8b18730]
    at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [paperspigot-1.8.8.jar:git-PaperSpigot-8b18730]
    at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [paperspigot-1.8.8.jar:git-PaperSpigot-8b18730]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [paperspigot-1.8.8.jar:git-PaperSpigot-8b18730]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: java.lang.NullPointerException
    at org.phantomapi.core.NestController.on(NestController.java:199) ~[?:?]
    at sun.reflect.GeneratedMethodAccessor49.invoke(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_101]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_101]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[paperspigot-1.8.8.jar:git-PaperSpigot-8b18730]
    ... 11 more
```

[Exception Cause](https://github.com/cyberpwnn/Phantom/blob/master/src/main/java/org/phantomapi/core/NestController.java#L199)
### NPE GChunk <> Chunk (Invalid World? Async to sync world problem?)

``` java
[13:07:54] [Craft Scheduler Thread - 18/WARN]: Exception in thread "Craft Scheduler Thread - 18" 
[13:07:54] [Craft Scheduler Thread - 18/WARN]: org.apache.commons.lang.UnhandledException: Plugin FastAsyncWorldEdit v16.08.25-5ed89f9-238 generated an exception while executing task 2495
    at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
    at org.phantomapi.event.NestChunkEvent.<init>(NestChunkEvent.java:21)
    at org.phantomapi.event.NestChunkUnloadEvent.<init>(NestChunkUnloadEvent.java:14)
    at org.phantomapi.core.NestController$3$1.sync(NestController.java:235)
    at org.phantomapi.sync.S$1.run(S.java:29)
    at org.phantomapi.Phantom$16.run(Phantom.java:1590)
    at org.phantomapi.Phantom$16.run(Phantom.java:1586)
    at com.boydti.fawe.object.RunnableVal.run(RunnableVal.java:14)
    at com.boydti.fawe.util.TaskManager$4.run(TaskManager.java:346)
    at com.boydti.fawe.util.TaskManager$4.run(TaskManager.java:342)
    at com.boydti.fawe.object.RunnableVal.run(RunnableVal.java:14)
    at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
    at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:349)
    at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:783)
    at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378)
    at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713)
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616)
    ... 1 more
```

**Comment by cyberpwnn** [comment]
It appears this happens under certain conditions. Here are some notes on this issue
- The Unloading chunk probably diddnt finish loading nest data when unloaded.
- This usually happens when the server starts, loading chunks, then unloading them when no one is online
